export const pbCases = {
  text: "PB案例学习",
  icon: "mdi:folder-play-outline",
  prefix: "cases/",
  link: "cases/",
  children: [
    {
      text: "窗口及基本控件",
      icon: "mdi:window-maximize",
      prefix: "winbasicctrl/",
      collapsible: true,
      children: [
        "01application-win-control",
        "02directory-browser",
        "03password-authentication",
        "04fileBrowser",
        "05pic-browser",
        "06drag-icon",
        "07flashing-text",
        "08drag-control",
        "09scroll-bar",
        "10progress-bar",
      ],
    },
    {
      text: "窗口及控件的应用",
      icon: "mdi:application-cog-outline",
      prefix: "winctrlapp/",
      collapsible: true,
      children: [
        "11animation-window",
        "12stopwatch",
        "13electronic-clock",
        "14use-num-usedate-limit",
        "15app-usenum-limit",
        "16set-system-time",
        "17color-dialog-box",
        "18ipaddress-edit",
        "19pic-button",
        "20hyperlink-button",
        "21lowercase-amount-conversion",
      ],
    },
    {
      text: "菜单及MDI窗口",
      icon: "mdi:menu-open",
      prefix: "menumdi/",
      collapsible: true,
      children: [
        "22voice-broadcast-amount",
        "23window-menu",
        "24graphics-menu",
        "25mdi-window-with-pictures",
        "26floating-toolbar",
        "27taskbar-hidden-display",
        "28right-click-menu",
        "29html-helpapp",
        "30dynamically-create-windows",
        "31dynamic-settings-menu",
        "32notepad",
      ],
    },
    {
      text: "数据窗口基本操作",
      icon: "mdi:table",
      prefix: "datawindow/",
      collapsible: true,
      children: [
        "33conn2oracle",
        "34conn2mysql",
        "35conn2access",
        "36conn2sqlite",
        "59conn2sqlserver",
        "37set-tab-color",
        "38set-tab-pic",
        "39char-display-data",
        "40window-zoom-display",
        "41dynamic-set-datawindow-style",
        "42use-the-tabs",
        "43use-list-view",
        "44use-dropdown-datawindow",
        "45dyn-create-datawindow",
      ],
    },
    {
      text: "数据窗口应用",
      icon: "mdi:table-cog",
      prefix: "datawindowapp/",
      collapsible: true,
      children: [
        "46edit-data-window",
        "47data-recovery",
        "48sortempmo",
        "49data-window-sort",
        "50use-datastore-sharedata",
        "51query-data",
        "52fuzzy-query-data",
        "53get-pinyin-fist",
        "54keyboard-simulation",
        "55save-data2word",
        "56save-data2excel",
        "57print-preview",
        "58report-print",
      ],
    },
  ],
};